<?php

namespace App;

use App\Mail\ProjectCreated;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $guarded = [];
//      Puede ser una opción para mandar mails apenas se crea pero no es la manera mas limpia
//      ya que no queda claro que sea responsabilidad del metodo de creación esta responsabilidad ver Seesaws
//      de esta cforma se genera acoplamiento
//    protected static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//
//        //Esto se ejecuta solo despues de que se creo un proyecto y se guardo en la db son eloquent events
//        static::created(function ($project) {
//            Mail::to($project->owner->email)->send(
//                new ProjectCreated($project)
//            );
//        });
//    }

    public function addTask($task)
    {
        $this->tasks()->create($task);
//        return Task::create([
//           'project_id' => $this->id,
//           'description' => $description
//        ]);
    }

    public function tasks()
    {
        return $this->hasMany(Task::class);
    }

    public function owner()
    {
        return $this->belongsTo(User::class);
    }
}
